theme: jekyll-theme-slate
title: Expert Collective
author: Enrique Shadah
email: enrique@expertcollective.org
description: > # this means to ignore newlines until "baseurl:"
  Our mission is to foster knowledge transfer from research institutions to society at large.

show_excerpts: false 
